Make boot scene branch
IKaRus8/IdleCampaign pull request #1
Opened 2023-10-27 19:02 UTC by VEkaterinaA

2023-10-28 10:17 UTC, IKaRus8 requested changes

2023-10-28 10:17 UTC, IKaRus8 commented on Assets/Resources/ProjectContext.prefab
А что за префаб контекста в папке ресурсов?

2023-10-28 10:17 UTC, IKaRus8 commented on Assets/Scripts/DI/Installers/ProjectInstaller.cs
> +            Container.Bind<ResourceLoadService>().AsSingle();
Почему лучше биндить интерфейс, а не реализацию?

2023-10-28 10:17 UTC, IKaRus8 commented on Assets/Scripts/UI/Services/ResourceLoadService.cs
> +        private static bool AssetExists(string key)
Было бы здорово, если бы ты разобралась, как проверять ассет до загрузки. Сейчас, если указать некорректный ключ, то выбросит ошибку

2023-10-28 10:17 UTC, IKaRus8 commented on Assets/Scripts/UI/Services/SpawnObjectAdressables.cs
> +public class SpawnObjectAdressables : MonoBehaviour
Что-то я совсем не понял назначение этого класса

2023-10-28 10:17 UTC, IKaRus8 commented on Assets/Scripts/UI/UIControllers/MainMenuController.cs
> +public class MainMenuController : MonoBehaviour
Этому классу не обязательно наследовать MonoBehaviour?

2023-10-31 09:23 UTC, VEkaterinaA commented on Assets/Resources/ProjectContext.prefab
Это контекст, который подгружается к каждой сцене, подумала, что такие классы, как загрузка ресурсов и сцен, должны существовать во всем проекте.

2023-10-31 09:55 UTC, VEkaterinaA commented on Assets/Scripts/DI/Installers/ProjectInstaller.cs
> +            Container.Bind<ResourceLoadService>().AsSingle();
Абстрагирование, нет привязки к определенной реализации, интерфейсом разграничиваем доступ к ней. Поправлю.

2023-10-31 10:03 UTC, VEkaterinaA commented on Assets/Scripts/UI/UIControllers/MainMenuController.cs
> +public class MainMenuController : MonoBehaviour
Этот класс работает с UIDocument, подгружает все элементы root. В целом, его можно вынести из этого объекта и добавить ссылку, но он все равно останется MonoBehaviour. Хотя можно через инсталлер передать ему ссылку на документ.

2023-10-31 10:04 UTC, VEkaterinaA commented on Assets/Scripts/UI/Services/ResourceLoadService.cs
> +        private static bool AssetExists(string key)
Хорошо

2023-10-31 10:11 UTC, VEkaterinaA commented on Assets/Scripts/UI/Services/SpawnObjectAdressables.cs
> +public class SpawnObjectAdressables : MonoBehaviour
Я так поняла при загрузке сцены должен быть класс, который отвечает за подгрузку всех ресурсов данной сцены, в нем же лежат все объекты, в которых должны создаваться подгружаемые префабы и список меток. Не находила хороших примеров, как это сделать по другому, поэтому реализовала так.

2023-11-07 17:24 UTC, IKaRus8 requested changes

2023-11-07 17:24 UTC, IKaRus8 commented on Assets/Scripts/UI/Models/UIContainer.cs
> +    public Transform GetEnvironmnetParent()
Почему бы не сделать через проперти?

2023-11-07 17:24 UTC, IKaRus8 commented on Assets/Scripts/DI/Installers/ProjectInstaller.cs
> +            AddressablesManager.InitAddressables();
Этот класс занимается биндингом классов. В нем не должно быть другой логики. И для чего здесь статика, если мы запускать будем его один раз?

2023-11-07 17:24 UTC, IKaRus8 commented on Assets/Scripts/UI/Services/SceneLoader.cs
> +public class SceneLoader : MonoBehaviour
Зачем ему нужно быть монобехом? Не вижу ожидания загрузки этих ассетов. Может ли у нас загрузиться сцена игры без игрока и окружения?

2023-11-07 17:59 UTC, VEkaterinaA commented on Assets/Scripts/UI/Models/UIContainer.cs
> +    public Transform GetEnvironmnetParent()
Ага, думала нельзя использовать свойства, но можно использовать [field: SerializeField].

2023-11-08 07:58 UTC, IKaRus8 commented on Assets/Scripts/UI/Models/UIContainer.cs
> +    public Transform GetEnvironmnetParent()
<img width="533" alt="image" src="https://github.com/IKaRus8/IdleCampaign/assets/48439982/a750ef99-1036-4caf-998e-40bb662207b4">

2023-11-08 13:55 UTC, VEkaterinaA commented on Assets/Scripts/DI/Installers/ProjectInstaller.cs
> +            AddressablesManager.InitAddressables();
Ага, исправила

2023-11-08 15:22 UTC, VEkaterinaA commented on Assets/Scripts/UI/Services/SceneLoader.cs
> +public class SceneLoader : MonoBehaviour
Исправила

2023-11-10 07:39 UTC, IKaRus8 approved these changes

2023-11-10 07:40 UTC, merged