Make enemy unit branch
IKaRus8/IdleCampaign pull request #2
Opened 2023-11-15 13:28 UTC by VEkaterinaA

2023-11-16 15:54 UTC, IKaRus8 requested changes

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/GameState.cs
> +namespace GameLogic
Почему ты считаешь, что перечисление должно быть в папке логики?

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Interfaces/IEnemyFactory.cs
> +        IEnemy CreateEnemyOnScene(Vector3 enemyPosition);
OnScene как будто очевидно, можно без этой приписки

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Interfaces/IPresenceOfEnemy.cs
> +        ReactiveProperty<bool> EnemyOnScene { get;}
А где они еще могут быть? Может тут речь про EnemyNear?

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyFactory.cs
> +        private readonly IUIContainerPrefabs _uiPrefabs;
Что-то не понял назначение этого класса "UIContainerPrefabs"

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyFactory.cs
> +            _diContainer = diContainer;
используй IInstatiator

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyFactory.cs
> +            _uiContainerObjectsParents.EnemyContainerParent.localPosition = newPos;
Мы не должны менять что либо внутри контейнера объектов. Он для их предоставление только. Явно есть какой-то изъян архитектуры, если приходиться двигать паренты

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyFactory.cs
> +        public IEnemy SetCreatedEnemy(GameObject enemyObject)
Нейминг запутывает. Я думаю. дело в не до конца продуманной логике

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyFactory.cs
> +            Enemy enemy = new Enemy();
Может ли Enemy не содержать enemyObject?
Тут стоит подумать, не проще ли будет делать Enemy monoBehaviour

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            _enemySquadInfo = enemyInfo;
Не понял, что за инфо получает менеджер?

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            _disposable = segmentContainer.ActiveRoadRx.Subscribe(SpawnEnemy);
ActiveRoadRx это разве не та, на которой сейчас находиться игрок? Нам нужно спавнить врагов заранее

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            if (!EnemyOnScene.Value)
Как-то все непонятно из-за нейминга

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/SpawnEnemy.cs
> +    public class SpawnEnemy : ISpawnEnemy
понятнее будет  EnemySpawner

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/SpawnEnemy.cs
> +        public IEnemy EnemyGeneration(Vector3 enemyPosition)
Тогда уже просто Spawn()

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerBattleState.cs
> +    public class PlayerBattleState : PlayerBaseState
Не совсем понимаю назначение этого класса

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +            var currentState = _allStates.FirstOrDefault(s=>s is T);
В целом ок, но рефлексией лучше не увлекаться. У тебя дженерик класс просто чтобы определить тип. В таком случае, правильнее или енам передавать или id

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/RandomGeneration.cs
> +        public bool IsCreateObject(float chance)
Этот метод можно применять только для создания врагов?

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/UI/Interfaces/IUIContainerObjectsParents.cs
> +        Transform EnemyContainerParent { get; }
не понятно, что это по названию

2023-11-16 15:54 UTC, IKaRus8 commented on Assets/Scripts/UI/Models/UIContainer.cs
> +    public GameObject EnemyPrefab { get; set; }
выглядит лишним

2023-11-20 10:31 UTC, IKaRus8 requested changes

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            isSpawnEnemy = true;
Этот флаг еще нужен?

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            if (_enemyProvider.Enemies.Count == 0)
не может быть больше одного отряда врагов на пути?

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +        public void EnemyDestroy(int index)
Почему по индексу? как мне снаружи узнать индекс?

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemySpawner.cs
> +        public EnemySpawner(RandomGeneration randomGeneration, IEnemyFactory createEnemy)
в большинстве случаев, переменная называется также, как и объект:
IEnemyFactory enemyFactory.
один раз придумай понятное имя для класса и потом не нужно будет придумывать новое. И не будет странных записей _createEnemy.CreateEnemy

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +        private bool isEnemyNotExist => _enemyProvider.Enemies.Count == 0;
подобные вещи лучше выносить в провайдер. В провайдере не только список врагов, но и выходящая инфа

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +                var enemyPositionZ = -_enemyProvider.Enemies[0].enemyObject.transform.localPosition.z;
Очень плохая практика залазить в объект так далеко.
_enemyProvider.Enemies[0].enemyObject.transform.localPosition.z
Если тебе приходится сталкиваться с таким, значит архитектура построена неправильно

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +            GameState gameState = GameState.Normal;
var gameState = isEnemyInApproachRadius ? GameState.Battle : GameState.Normal;

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +            if (_currentState._gameState != gameState)
Запись _currentState._gameState нарушает инкапсуляцию. Публичные поля представляются через проперти

2023-11-20 10:31 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/TestService.cs
> +    public class TestService
Наверное, не должно было попасть

2023-11-20 12:12 UTC, VEkaterinaA commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            isSpawnEnemy = true;
Когда игрок подходит к вражескому отряду, создаются еще два сегмента, он нужен для того, чтобы не создавались еще отряды, пока существует хотя бы один. Иначе может быть так, что на двух - трех сегментах подряд будут стоять отряды. Если это не нужно, уберу

2023-11-20 12:50 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/EnemyServices/EnemyManager.cs
> +            isSpawnEnemy = true;
Почему бы не быть трем врагам подряд? По текущей логике, у нас после каждого врага, два сегмента без врагов. Определенно, так не должно быть

2023-11-20 17:16 UTC, IKaRus8 commented on Assets/Scripts/GameInfoModels/Interfaces/IEnemyProvider.cs
> +        public bool isEnemyNotExist => Enemies.Count == 0;
Зачем логика в интерфейсе?

2023-11-20 17:16 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerBaseState.cs
> +        public GameState _gameState { get; }
Проперти называются с заглавной буквы - GameState {get;}

2023-11-20 17:16 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Services/PlayerState/PlayerState.cs
> +                var enemyPositionZ = -_enemyProvider.Enemies[0].enemyPosition.z;
В целом ок, но почему бы просто не использовать Vector3.Distance()?

2023-11-21 09:13 UTC, IKaRus8 approved these changes

2023-11-21 09:13 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Controllers/PlayerSquadController.cs
> +        public float ApproachRadius;
Это поле должно быть публичным? 
Только проперти называются с большой буквы.
private float _approachRadius;
public float ApproachRadius {get; set;}

2023-11-21 09:20 UTC, VEkaterinaA commented on Assets/Scripts/GameLogic/Controllers/PlayerSquadController.cs
> +        public float ApproachRadius;
Это поле публичное для того, чтобы менять его на сцене. Не нужно?

2023-11-21 09:25 UTC, IKaRus8 commented on Assets/Scripts/GameLogic/Controllers/PlayerSquadController.cs
> +        public float ApproachRadius;
Ты ведь до этого уже делала такие поля через
[SerializedField]
private float _approachRadius;

2023-11-21 10:30 UTC, merged